import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '@/store/provider'
import { Header } from '@/widgets/Header'
import { Footer } from '@/widgets/Footer'
import { Provider } from '@/components/Providers/Providers'

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
      <Providers>
        <body>
          <header>
            <Header />
          </header>
          <main>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </Providers>
      </Provider>
    </html>
  )
}